apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-3
  namespace: letmesee
  labels:
    app: hello-world-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-3
  template:
    metadata:
      labels:
        app: hello-world-3
    spec:
      containers:
      - name: hello-world-3
        image: randersonlemos/flaskhelloworld:latest
        command: ["python", 'main.py', '--phrase', 'It is we!!!']
        ports:
        - containerPort: 82
        resources:
          limits:
            memory: "128Mi"
            cpu: "80m"
        volumeMounts:
          - mountPath: "/app/data"
            name: recorder-data
      volumes:
      - name: recorder-data
        persistentVolumeClaim:
          claimName: nfs-pvc
