apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: letmesee
  labels:
    app: hello-world
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-world
  # type: LoadBalancer
