apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: letmesee
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: randersonlemos/flaskhelloworld:latest
        command: ["python", 'main.py']
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "80m"
        volumeMounts:
          - mountPath: "/app/data"
            name: recorder-data
      volumes:
      - name: recorder-data
        persistentVolumeClaim:
          claimName: nfs-pvc
